<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-07-31 12:25

$extensionPath = t3lib_extMgm::extPath('ictiextbase');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_ictiextbase_domain_model_csvmediaitem' => $extensionClassesPath . 'Domain/Model/CsvMediaItem.php',
	'tx_ictiextbase_domain_model_csvmediaiterator' => $extensionClassesPath . 'Domain/Model/CsvMediaIterator.php',
	'tx_ictiextbase_domain_model_mediainterface' => $extensionClassesPath . 'Domain/Model/MediaInterface.php',
	'tx_ictiextbase_helpers_datetime' => $extensionClassesPath . 'Helpers/DateTime.php',
	'tx_ictiextbase_helpers_datetimetest' => $extensionPath . 'Tests/Unit/Helpers/DateTimeTest.php',
	'tx_ictiextbase_helpers_exception' => $extensionClassesPath . 'Helpers/Exception.php',
	'tx_ictiextbase_helpers_exception_tablenotintca' => $extensionClassesPath . 'Helpers/Exception/TableNotInTCA.php',
	'tx_ictiextbase_helpers_preprocessrequesthook' => $extensionClassesPath . 'Helpers/PreprocessRequestHook.php',
	'tx_ictiextbase_helpers_tca' => $extensionClassesPath . 'Helpers/Tca.php',
	'tx_ictiextbase_helpers_tcaobject' => $extensionClassesPath . 'Helpers/TcaObject.php',
	'tx_ictiextbase_helpers_tcastiobject' => $extensionClassesPath . 'Helpers/TcaStiObject.php',
	'tx_ictiextbase_service_abstractfiltersservice' => $extensionClassesPath . 'Service/AbstractFiltersService.php',
	'tx_ictiextbase_service_abstractlookupservice' => $extensionClassesPath . 'Service/AbstractLookupService.php',
	'tx_ictiextbase_service_filter' => $extensionClassesPath . 'Service/Filter.php',
	'tx_ictiextbase_service_serviceinterface' => $extensionClassesPath . 'Service/ServiceInterface.php',
	'tx_ictiextbase_view_variantview' => $extensionClassesPath . 'View/VariantView.php',
	'tx_ictiextbase_viewhelpers_benchmarkviewhelper' => $extensionClassesPath . 'ViewHelpers/BenchmarkViewHelper.php',
	'tx_ictiextbase_viewhelpers_canonicaluriviewhelper' => $extensionClassesPath . 'ViewHelpers/CanonicaluriViewHelper.php',
	'tx_ictiextbase_viewhelpers_cobjectviewhelper' => $extensionClassesPath . 'ViewHelpers/CObjectViewHelper.php',
	'tx_ictiextbase_viewhelpers_flvplayerviewhelper' => $extensionClassesPath . 'ViewHelpers/FlvplayerViewHelper.php',
	'tx_ictiextbase_viewhelpers_form_selectviewhelper' => $extensionClassesPath . 'ViewHelpers/Form/SelectViewHelper.php',
	'tx_ictiextbase_viewhelpers_format_bytesviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/BytesViewHelper.php',
	'tx_ictiextbase_viewhelpers_format_cdataviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/CdataViewHelper.php',
	'tx_ictiextbase_viewhelpers_format_htmlentitiesviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/HtmlentitiesViewHelper.php',
	'tx_ictiextbase_viewhelpers_format_rawviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/RawViewHelper.php',
	'tx_ictiextbase_viewhelpers_format_strftimeviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/StrftimeViewHelper.php',
	'tx_ictiextbase_viewhelpers_format_urlencodeviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/UrlencodeViewHelper.php',
	'tx_ictiextbase_viewhelpers_formviewhelper' => $extensionClassesPath . 'ViewHelpers/FormViewHelper.php',
	'tx_ictiextbase_viewhelpers_headercontentviewhelper' => $extensionClassesPath . 'ViewHelpers/HeaderContentViewHelper.php',
	'tx_ictiextbase_viewhelpers_htmltitleviewhelper' => $extensionClassesPath . 'ViewHelpers/HtmltitleViewHelper.php',
	'tx_ictiextbase_viewhelpers_link_mediaviewhelper' => $extensionClassesPath . 'ViewHelpers/Link/MediaViewHelper.php',
	'tx_ictiextbase_viewhelpers_orderbyviewhelper' => $extensionClassesPath . 'ViewHelpers/OrderByViewHelper.php',
	'tx_ictiextbase_viewhelpers_page_content_getviewhelper' => $extensionClassesPath . 'ViewHelpers/Page/Content/GetViewHelper.php',
	'tx_ictiextbase_viewhelpers_page_content_renderviewhelper' => $extensionClassesPath . 'ViewHelpers/Page/Content/RenderViewHelper.php',
	'tx_ictiextbase_viewhelpers_widget_controller_loadselectvaluescontroller' => $extensionClassesPath . 'ViewHelpers/Widget/Controller/LoadSelectValuesController.php',
	'tx_ictiextbase_viewhelpers_widget_controller_objectlimitcontroller' => $extensionClassesPath . 'ViewHelpers/Widget/Controller/ObjectLimitController.php',
	'tx_ictiextbase_viewhelpers_widget_controller_paginatecontroller' => $extensionClassesPath . 'ViewHelpers/Widget/Controller/PaginateController.php',
	'tx_ictiextbase_viewhelpers_widget_loadselectvaluesviewhelper' => $extensionClassesPath . 'ViewHelpers/Widget/LoadSelectValuesViewHelper.php',
	'tx_ictiextbase_viewhelpers_widget_objectlimitviewhelper' => $extensionClassesPath . 'ViewHelpers/Widget/ObjectLimitViewHelper.php',
	'tx_ictiextbase_viewhelpers_widget_paginateviewhelper' => $extensionClassesPath . 'ViewHelpers/Widget/PaginateViewHelper.php',
);
?>